apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pod
  labels:
    tag:  my-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      tag:  my-pod
  template:
    metadata:
      labels:
        tag:  my-pod
    spec:
      containers:
      - name: udacity-capstone-container
        image: 884543467033.dkr.ecr.us-east-1.amazonaws.com/udacity-capstone:REPLACE_WITH_CI_WORKFLOW_ID
        ports:
        - containerPort: 80
        imagePullPolicy: "Always"
        env:
          - name: CI_WORKFLOW_ID
            value: REPLACE_WITH_CI_WORKFLOW_ID
